### ISSUE TITLE
Use UUID instead of Date.now

### ISSUE THREAD

**Issue by davidcostadev** [Sm03leBr00t/react-todo-application#1]
Hello. Great job on your article. This is just a suggestion. Using UUID as ID is can guarantee that ID is unique. So you will not have problem with keys. 

https://github.com/Sm03leBr00t/react-todo-application/blob/570f6358c3f2702ad3fcc2ecf5b91b3bb057626d/src/components/todolist.js#L13

**Comment by Sm03leBr00t** [comment]
Thank you for actually looking through the code. I thought of a very quick way to get an id. But you are right, we really want the id to be unique, especially when it comes to the database! I will address this right now :) Keep it up :+1:

**Comment by Sm03leBr00t** [comment]
Well I hope that's it :smiley: . If I miss anything else, feel free do open up an issue :+1:
