### ISSUE TITLE
How do I populate the ToDo list with an API call?

### ISSUE THREAD

**Issue by captmomo** [Sm03leBr00t/react-todo-application#2]
Is it possible to initialize the context todo list with an api call?

**Comment by Sm03leBr00t** [comment]
It is possible by using an 'useEffect' hook or 'componentDidMount'. I will do an example later when I got time 😄🤙 but good question!

**Comment by Sm03leBr00t** [comment]
Look into the `todolist.js`, I added a fake API call and added the incoming todo items to our list. You could do anything there like comparing changes or whatever javascript allows. :+1: I hope your question is solved if not please feel free to reach out again! :smile:

**Comment by captmomo** [comment]
Thank you 🙌🏾
